# docker-compose.yml
version: '3'

services:
  generator:
    build:
      context: ./generator
    volumes:
      - log-data:/logs
    command: python generator.py --format apache --rate 5 --output /logs/app.log

  collector:
    build:
      context: ./collector
    volumes:
      - log-data:/logs
      - collected-data:/data/collected
    depends_on:
      - generator
    command: python collector.py --source /logs/app.log --output-dir /data/collected --interval 2

  parser:
    build:
      context: ./parser
    volumes:
      - collected-data:/data/collected
      - parsed-data:/data/parsed
    depends_on:
      - collector
    command: python parser.py --input-dir /data/collected --output-dir /data/parsed --format apache --interval 3

  storage:
    build:
      context: ./storage
    volumes:
      - parsed-data:/data/parsed
      - storage-data:/data/storage
    depends_on:
      - parser
    command: python storage.py --input-dir /data/parsed --storage-dir /data/storage --rotation-size 1 --rotation-hours 1 --interval 5

  query:
    build:
      context: ./query
    volumes:
      - storage-data:/data/storage
    depends_on:
      - storage
    # Command will be provided when running interactively

  integration:
    build:
      context: .
    volumes:
      - log-data:/logs
      - collected-data:/data/collected
      - parsed-data:/data/parsed
      - storage-data:/data/storage
    ports:
      - "8000:8000"
    depends_on:
      - generator
      - collector
      - parser
      - storage

volumes:
  log-data:
  collected-data:
  parsed-data:
  storage-data: