# Log Enrichment Rules Configuration
# Defines which metadata to include based on log characteristics

rules:
  - name: "critical_error_enrichment"
    conditions:
      log_level: ["CRITICAL", "FATAL"]
      message_contains: ["error", "fail", "crash", "panic"]
    actions:
      include_performance: true
      include_environment: true
      include_detailed_system: true
      include_network: true

  - name: "database_error_enrichment"
    conditions:
      message_contains: ["database", "db", "sql", "connection", "timeout"]
    actions:
      include_performance: true
      include_environment: true

  - name: "authentication_enrichment"
    conditions:
      message_contains: ["auth", "login", "user", "session", "token"]
    actions:
      include_environment: true
      include_security_context: true

  - name: "performance_warning_enrichment"
    conditions:
      log_level: ["WARN", "WARNING"]
      message_contains: ["memory", "cpu", "disk", "slow", "timeout"]
    actions:
      include_performance: true

  - name: "default_info_enrichment"
    conditions:
      log_level: ["INFO"]
    actions:
      include_environment: true
