# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_entry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'log_entry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flog_entry.proto\x12\rlogprocessing\"\xd1\x01\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x12\x18\n\x10response_time_ms\x18\x06 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x07 \x01(\x05\x12\x30\n\x0cuser_context\x18\x08 \x01(\x0b\x32\x1a.logprocessing.UserContext\x12\x0c\n\x04tags\x18\t \x03(\t\"Z\n\x0bUserContext\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x12\n\nuser_agent\x18\x04 \x01(\t\"_\n\x08LogBatch\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.logprocessing.LogEntry\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x17\n\x0f\x62\x61tch_timestamp\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_entry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=35
  _globals['_LOGENTRY']._serialized_end=244
  _globals['_USERCONTEXT']._serialized_start=246
  _globals['_USERCONTEXT']._serialized_end=336
  _globals['_LOGBATCH']._serialized_start=338
  _globals['_LOGBATCH']._serialized_end=433
# @@protoc_insertion_point(module_scope)
