

services:
  log-generator:
    build:
      context: ./log-generator
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_FILE=/app/logs/app.log
      - ENTRIES_PER_SECOND=2
    restart: unless-stopped

  log-collector:
    build:
      context: ./log-collector
    volumes:
      - ./logs:/app/logs:ro  # Read-only access to logs
      - ./collected_logs:/app/collected_logs
    command: --log-files /app/logs/app.log --output-dir /app/collected_logs
    depends_on:
      - log-generator
    restart: unless-stopped
