version: '3'

services:
  udp-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9999:9999/udp"
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - log-network
    command: ["python", "-m", "src.server.udp_server", "--dashboard"]

  udp-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - udp-server
    networks:
      - log-network

  load-test:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - udp-server
    networks:
      - log-network
    command: ["python", "-m", "src.tests.load_test", "--server", "udp-server", "--logs", "50000", "--rate", "5000", "--clients", "8"]

networks:
  log-network:
    driver: bridge