version: '3'

services:
  log-receiver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python src/server.py
    ports:
      - "5000:5000"
    networks:
      - log-network
    volumes:
      - ../logs:/app/logs

  log-shipper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python src/client.py --server log-receiver --port 5000 --batch-size 100 --batch-interval 5 --compression gzip --level 6 --rate 50
    networks:
      - log-network
    depends_on:
      - log-receiver

networks:
  log-network:
