# docker/docker-compose.yml
version: '3'

services:
  log-storage:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../logs:/app/logs
    ports:
      - "8080:8080"  # For future web interface