version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: log_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      PYTHONPATH: /app/src
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  log_producer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: log_producer
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ../config:/app/config:ro
    restart: unless-stopped

volumes:
  rabbitmq_data:
