
services:
  log-generator:
    build:
      context: ./src/services/log-generator
    volumes:
      - ./src/services/log-generator:/app
      - ./logs:/logs
    environment:
      - LOG_RATE=10
      - CONSOLE_OUTPUT=true
      - OUTPUT_FILE=/logs/generated_logs.log