# MapReduce Framework Configuration

# Job Execution Settings
execution:
  default_workers: 4
  max_workers: 16
  chunk_size_mb: 64
  timeout_seconds: 300
  retry_attempts: 3

# Performance Settings
performance:
  batch_size: 1000
  memory_limit_mb: 1024
  enable_compression: true
  intermediate_cleanup: true

# Web Interface Settings
web:
  host: "0.0.0.0"
  port: 8080
  enable_websockets: true
  max_connections: 100

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/mapreduce.log"
  max_size_mb: 100
  backup_count: 5

# Storage Settings
storage:
  input_directory: "data/input"
  output_directory: "data/output"
  intermediate_directory: "intermediate"
  cleanup_after_hours: 24
