# week2/day11/docker-compose.yml
version: '3'

services:
  log-server:
    build:
      context: ../..
      dockerfile: week2/day11/Dockerfile.server
    ports:
      - "9999:9999/udp"
    networks:
      - log-network

  log-client:
    build:
      context: ../..
      dockerfile: week2/day11/Dockerfile.client
    environment:
      - SERVER_HOST=log-server
    depends_on:
      - log-server
    networks:
      - log-network

networks:
  log-network:
    driver: bridge