# docker-compose.yml

services:
  log-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - log-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 8888)); s.close()"]
      interval: 10s
      timeout: 5s
      retries: 3

  load-generator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.generator
    depends_on:
      log-server:
        condition: service_healthy
    volumes:
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=log-server
      - SERVER_PORT=8888
    networks:
      - log-network

networks:
  log-network:
    driver: bridge
