version: '3.8'

services:
  partition-1:
    build:
      context: .
      dockerfile: Dockerfile.partition
    container_name: partition-1
    ports:
      - "8081:8081"
    command: ["python", "-m", "src.partition_server", "partition_1", "8081"]
    volumes:
      - partition1_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - query_network

  partition-2:
    build:
      context: .
      dockerfile: Dockerfile.partition
    container_name: partition-2
    ports:
      - "8082:8082"
    command: ["python", "-m", "src.partition_server", "partition_2", "8082"]
    volumes:
      - partition2_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - query_network

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: query-coordinator
    ports:
      - "8080:8080"
    depends_on:
      partition-1:
        condition: service_healthy
      partition-2:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - query_network

volumes:
  partition1_data:
  partition2_data:

networks:
  query_network:
    driver: bridge
