services:
  log-server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9000:9000"
    networks:
      - log-network

  log-client:
    build: .
    environment:
      - SERVER_HOST=log-server
      - SERVER_PORT=9000
      - SHIPPING_MODE=continuous
    volumes:
      # Mount a logs directory for real-time log generation
      - ./logs:/app/logs
    networks:
      - log-network
    depends_on:
      - log-server

networks:
  log-network:
    driver: bridge